#!/usr/bin/python3
#SPDX-FileCopyrightText: 2023 Yuta Suzuki
#SPDX-License-Identifier: BSD-3-Clause

import sys

ans = 1   
for line in sys.stdin:
    try: 
        ans *= int(line)   
    except:
        ans *= float(line)

print(ans)

ans2 = 0
for line in sys.stdin:
    try:
        ans2 *= int(line)
    except:
        ans2 *= float(line)

print(ans2)
