#!/usr/bin/python3
#SPDX-FileCopyrightText: 2023 Yuta Suzuki
#SPDX-License-Identifier: BSD-3-Clause

import sys

ans = 1   
ans2 = 0

for line in sys.stdin:
    try: 
        num = int(line)
        ans *= num
        ans2 += num
    except:
        num2 = float(line)
        ans *= num2
        ans2 += num2
print(ans2)
print(ans)
